# Support WRN Cleaner by using the funding links below
# Developed and Maintained by Waren Gonzaga

issuehunt: WarenGonzaga/wrn-cleaner
custom: ['https://bmc.xyz/warengonzaga','https://paypal.me/warengonzagaofficial']
